environment:
   grid_size: 20
   obstacle_probability: 0.3
   actions: [0, 1, 2, 3]
   action_to_delta: {
      0: [0, -1],   # Up
      1: [1, 0],    # Right
      2: [0, 1],    # Down
      3: [-1, 0]    # Left
   }
   step_reward: -5.0
   goal_reward: 500.0
   invalid_move_penalty: -10.0

agent:
   alpha: 0.2
   gamma: 0.995
   epsilon: 1.0
   epsilon_min: 0.002
   epsilon_decay: 0.995

trainer:
   max_steps_per_episode: 200
   reward_avg_window: 100
